/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DEXInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "getReserves"
      | "lpToken"
      | "removeLiquidity"
      | "reserveA"
      | "reserveB"
      | "spotPrice"
      | "swapAforB"
      | "swapBforA"
      | "tokenA"
      | "tokenB"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "reserveA", values?: undefined): string;
  encodeFunctionData(functionFragment: "reserveB", values?: undefined): string;
  encodeFunctionData(functionFragment: "spotPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapAforB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBforA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tokenA", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenB", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserveA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reserveB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spotPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapAforB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapBforA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenB", data: BytesLike): Result;
}

export interface DEX extends BaseContract {
  connect(runner?: ContractRunner | null): DEX;
  waitForDeployment(): Promise<this>;

  interface: DEXInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [amountA: BigNumberish, amountB: BigNumberish],
    [void],
    "nonpayable"
  >;

  getReserves: TypedContractMethod<[], [[bigint, bigint]], "view">;

  lpToken: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  reserveA: TypedContractMethod<[], [bigint], "view">;

  reserveB: TypedContractMethod<[], [bigint], "view">;

  spotPrice: TypedContractMethod<[], [bigint], "view">;

  swapAforB: TypedContractMethod<
    [amountIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapBforA: TypedContractMethod<
    [amountIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenA: TypedContractMethod<[], [string], "view">;

  tokenB: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [amountA: BigNumberish, amountB: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "lpToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "spotPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapAforB"
  ): TypedContractMethod<[amountIn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapBforA"
  ): TypedContractMethod<[amountIn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenB"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
