/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbitrageSol from "./Arbitrage.sol";
export type { arbitrageSol };
export type { DEX } from "./DEX";
export type { LPToken } from "./LPToken";
export type { Token } from "./Token";
